
name: yspsouthaichi

on:
  push:
    branches:
      - master

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftp.yspsouthaichi.org
        FTP_USERNAME: yspsouthaichi
        FTP_PASSWORD: zrvz4171
        ARGS: --delete